### ISSUE TITLE
Color of node

### ISSUE THREAD

**Issue by mogo062** [singhalavi/graph-tree#1]
Hi,
I have a question about a node color. is it  possible to add  in list predifined a new color ?.

**Comment by singhalavi** [comment]
Hi,

As of now i have added only grey, red and green colors. You cant add them
dynamically.
I am planning to add few more colors in the list, if you have any
preference or suggestions let me know

**Comment by mogo062** [comment]
thanks for this answer
My problem it's with the color, I 'm trying to use your add-on in my web application that to monitor many jobs.  
their jobs return the different status: aborted --> RED, running--> BLUE, WAIT--> yellow and correct executed --> GREEN, disabled --> GREY.
Can you please adding their colors ?

**Comment by singhalavi** [comment]
Fixed in version 0.0.4

**Comment by mogo062** [comment]
thanks for this new revision
