### ISSUE TITLE
node dimension

### ISSUE THREAD

**Issue by mogo062** [singhalavi/graph-tree#2]
Hi,
I will return to you with a new question about the size of node.
is it possible to modify the height and the width node? if yes how to make?
and can you add me a new color blue sky in your plugin

thanks for all

**Comment by singhalavi** [comment]
As of now its not, but will provide this option in the next version.

**Comment by singhalavi** [comment]
Use latest version 0.0.5
Now you can define the color yourself, no predefined colors
 graphJSComponent.addNode("apple", "Apple", "level 2", null, "fruits");//third child of node with id fruits
                        graphJSComponent.getNodeProperties("apple").put("title", "One apple a day, keeps the doctor away"); 
                        graphJSComponent.getNodeProperties("apple").put("fill", "red");

you can also change the node size as below
 GraphJSComponent graphJSComponent = new GraphJSComponent();
        graphJSComponent.setNodesSize(120, 50);
