### ISSUE TITLE
How we give Icon on Node?

### ISSUE THREAD

**Issue by sachinsurve11** [singhalavi/graph-tree#3]
I am trying to provide image or icon on node. How we can give that. If I am providing url as string for icon, it is not rendering image for same.

**Comment by singhalavi** [comment]
use 0.0.7 version
and give any image url in addNode() method, you can also set icon width and height as below
graphJSComponent.getNode(id).setIconWidth(50);
graphJSComponent.getNode(id).setIconHeight(50);

default is 16x16.

**Comment by soundar-gnts** [comment]
Hi singhalavi,
I am trying to get image in node.but its not set it.Plese provide sample code.
