### ISSUE TITLE
Maher Daoud

### ISSUE THREAD

**Issue by maherdaoud** [singhalavi/graph-tree#5]
Hi, i tried to add a function isExist() to check if a node exists in order to connected to another node, can you help me to add it to my project 
Note i am using maven 
public boolean isExist(String id){
          GraphJsNode node = nodeMap.get(id);
          if(node == null) return false;
          return true;
}  
add this function to GraphJSComponent class
thank you :)

**Comment by singhalavi** [comment]
please use 0.0.7 version
use isNodePresent() api
